--CREATE TABLE users (
--    username VARCHAR(50) PRIMARY KEY,
--    password VARCHAR(500) NOT NULL,
--    enabled BOOLEAN NOT NULL
--);
--
--CREATE TABLE authorities (
--    username VARCHAR(50) NOT NULL,
--    authority VARCHAR(50) NOT NULL,
--    CONSTRAINT fk_authorities_users FOREIGN KEY (username) REFERENCES users(username)
--);
--
--CREATE UNIQUE INDEX ix_auth_username ON authorities (username, authority);
--
---- Inserting users
--INSERT INTO users (username, password, enabled) VALUES
--    ('sumanth', '12345', true),
--    ('sai', '123', true),
--    ('vyshu', '123', true);
--
---- Inserting authorities
--INSERT INTO authorities (username, authority) VALUES
--    ('sumanth', 'ROLE_USER'),
--    ('sai', 'ROLE_USER'),
--    ('vyshu', 'ROLE_ADMIN');
